version: "2"

services:
  redis:
    image: redis:alpine
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  worker:
    build: .
    command: celery -A growthstreet.celery worker
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - db
      - redis
