version: "2"

services:
  redis:
    image: redis:alpine
    cpu_shares: 100
    mem_limit: 524288000
  web:
    image: rollokb/growth-street-test:latest 
    cpu_shares: 200 
    mem_limit: 524288000
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.4
    hostname: db
    cpu_shares: 100
    mem_limit: 524288000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  worker:
    cpu_shares: 100
    mem_limit: 524288000
    image: rollokb/growth-street-test:latest
    command: celery -A growthstreet.celery worker
    links:
      - redis
    depends_on:
      - db
      - redis
